spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to BS23 Bank loans related prod APIs "
  contactDetails:
    name: "Arif - Product Owner"
    email: "arif@bs23.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956